const Ziggy = {"url":"http:\/\/localhost:9400","port":9400,"defaults":{},"routes":{"debugbar.openhandler":{"uri":"_debugbar\/open","methods":["GET","HEAD"]},"debugbar.clockwork":{"uri":"_debugbar\/clockwork\/{id}","methods":["GET","HEAD"]},"debugbar.telescope":{"uri":"_debugbar\/telescope\/{id}","methods":["GET","HEAD"]},"debugbar.assets.css":{"uri":"_debugbar\/assets\/stylesheets","methods":["GET","HEAD"]},"debugbar.assets.js":{"uri":"_debugbar\/assets\/javascript","methods":["GET","HEAD"]},"debugbar.cache.delete":{"uri":"_debugbar\/cache\/{key}\/{tags?}","methods":["DELETE"]},"auth.login.view":{"uri":"auth\/login","methods":["GET","HEAD"]},"auth.login.active":{"uri":"auth\/login","methods":["POST"]},"auth.register.view":{"uri":"auth\/register","methods":["GET","HEAD"]},"auth.register.active":{"uri":"auth\/register","methods":["POST"]},"auth.logout":{"uri":"auth\/logout","methods":["POST"]},"auth.validation":{"uri":"auth\/validation\/{member}","methods":["GET","HEAD"]},"auth.social.login":{"uri":"auth\/social-login\/{social_provider}","methods":["GET","HEAD"]},"auth.social.callback":{"uri":"auth\/social-callback","methods":["GET","HEAD"]},"dashboard.index":{"uri":"dashboard\/{path?}","methods":["GET","HEAD"]},"dashboard.api.media.index":{"uri":"dashboard\/api\/v1\/media\/index","methods":["GET","HEAD"]},"dashboard.api.media.create":{"uri":"dashboard\/api\/v1\/media\/create","methods":["POST"]},"dashboard.api.media.destroy":{"uri":"dashboard\/api\/v1\/media\/destroy","methods":["DELETE"]},"dashboard.api.product.show":{"uri":"dashboard\/api\/v1\/product\/{product}","methods":["GET","HEAD"]},"dashboard.api.product.destroy":{"uri":"dashboard\/api\/v1\/product\/{product}","methods":["DELETE"],"bindings":{"product":"id"}},"dashboard.api.product.store":{"uri":"dashboard\/api\/v1\/product\/store\/{product?}","methods":["POST"],"bindings":{"product":"id"}}}};

if (typeof window !== 'undefined' && typeof window.Ziggy !== 'undefined') {
    for (let name in window.Ziggy.routes) {
        Ziggy.routes[name] = window.Ziggy.routes[name];
    }
}

export { Ziggy };
